baseURL = "https://athul.github.io/archie/"
languageCode = "en-us"
title = "Mano Sundar M"
theme="archie"
copyright = "© Mano Sundar "
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome to MindfulTechie , a personal blog about my experiences and insights in the ever-evolving world of technology. From software development to consumer gadgets, I share my passion for technology and explore its impact on our daily lives. Join me on this journey of discovery and stay tuned for engaging articles, tutorials, and reviews."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/manosundarmanivel"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/manivel_mano"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/manosundarmanivel"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/manosundarmanivel/"




# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4